"""new injection

Revision ID: 29c4784c8985
Revises: f5448bde14ae
Create Date: 2024-04-27 19:31:27.726184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c4784c8985'
down_revision = 'f5448bde14ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lpn_tag_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_class', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trip_cost', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fleet_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rego', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('res', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ref', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('update', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dropoff', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('day', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dropoff_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pickup', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pickup_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('time_c13', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vehicle', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('colour', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('items', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('insurance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('departure', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('next_rental', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pickup_date_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dropoff_date_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rcm_rego', sa.String(), nullable=True))
        batch_op.alter_column('# Days',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('Pickup')
        batch_op.drop_column('Vehicle Class')
        batch_op.drop_column('Fleet ID')
        batch_op.drop_column('Dropoff Date Time')
        batch_op.drop_column('Colour')
        batch_op.drop_column('Vehicle')
        batch_op.drop_column('LPN/Tag number')
        batch_op.drop_column('Category')
        batch_op.drop_column('Day')
        batch_op.drop_column('Trip Cost')
        batch_op.drop_column('Res.')
        batch_op.drop_column('Details')
        batch_op.drop_column('Rego')
        batch_op.drop_column('Start Date')
        batch_op.drop_column('Update')
        batch_op.drop_column('Dropoff')
        batch_op.drop_column('Ref.')
        batch_op.drop_column('Insurance')
        batch_op.drop_column('Date')
        batch_op.drop_column('Pickup Date Time')
        batch_op.drop_column('Departure')
        batch_op.drop_column('Notes')
        batch_op.drop_column('Dropoff Date')
        batch_op.drop_column('Pickup Date')
        batch_op.drop_column('Time')
        batch_op.drop_column('End Date')
        batch_op.drop_column('Status')
        batch_op.drop_column('Next Rental')
        batch_op.drop_column('#')
        batch_op.drop_column('Items')
        batch_op.drop_column('Time_c13')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Time_c13', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Items', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('#', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Next Rental', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('End Date', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Time', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Pickup Date', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Dropoff Date', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Notes', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Departure', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Pickup Date Time', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Date', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Insurance', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Ref.', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Dropoff', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Update', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Start Date', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Rego', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Details', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Res.', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Trip Cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Day', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Category', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LPN/Tag number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Vehicle', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Colour', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Dropoff Date Time', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Fleet ID', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Vehicle Class', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Pickup', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('# Days',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('rcm_rego')
        batch_op.drop_column('dropoff_date_time')
        batch_op.drop_column('pickup_date_time')
        batch_op.drop_column('next_rental')
        batch_op.drop_column('departure')
        batch_op.drop_column('insurance')
        batch_op.drop_column('items')
        batch_op.drop_column('colour')
        batch_op.drop_column('vehicle')
        batch_op.drop_column('category')
        batch_op.drop_column('time_c13')
        batch_op.drop_column('pickup_date')
        batch_op.drop_column('pickup')
        batch_op.drop_column('time')
        batch_op.drop_column('dropoff_date')
        batch_op.drop_column('day')
        batch_op.drop_column('dropoff')
        batch_op.drop_column('status')
        batch_op.drop_column('notes')
        batch_op.drop_column('update')
        batch_op.drop_column('ref')
        batch_op.drop_column('res')
        batch_op.drop_column('rego')
        batch_op.drop_column('date')
        batch_op.drop_column('end_date')
        batch_op.drop_column('fleet_id')
        batch_op.drop_column('trip_cost')
        batch_op.drop_column('vehicle_class')
        batch_op.drop_column('lpn_tag_number')
        batch_op.drop_column('details')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
