"""empty message

Revision ID: d69259184cfa
Revises: a60b65ba32b7
Create Date: 2024-04-30 19:50:15.765962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69259184cfa'
down_revision = 'a60b65ba32b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.alter_column('# Days',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rawdata', schema=None) as batch_op:
        batch_op.alter_column('# Days',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
