"""empty message

Revision ID: f5448bde14ae
Revises: 
Create Date: 2024-04-23 18:45:40.371046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5448bde14ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary',
    sa.Column('contract_number', sa.Integer(), nullable=False),
    sa.Column('num_of_rows', sa.Integer(), nullable=True),
    sa.Column('sum_of_toll_cost', sa.Float(), nullable=True),
    sa.Column('total_toll_contract_cost', sa.Float(), nullable=True),
    sa.Column('pickup_date_time', sa.DateTime(), nullable=True),
    sa.Column('dropoff_date_time', sa.DateTime(), nullable=True),
    sa.Column('admin_fee', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('contract_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.drop_table('user')
    op.drop_table('summary')
    # ### end Alembic commands ###
